config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions"
  }
  get '/users', to: redirect("/users/sign_up")
  
  namespace :api, { format: 'json' } do
    # resources :favorites, only: [:index, :create, :destroy]
    post '/favorites', to: 'favorites#create'
    delete '/favorite/delete', to: 'favorites#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'displays#home'
  resources :displays do
    collection do
      get 'home'
      get 'company'
      get 'contact'
      get 'info'
    end
  end
  
  get 'company', to: 'displays#company'
  get 'contact', to: 'displays#contact'
  get 'info', to: 'displays#info'
  get 'items', to: 'items#index'
  get 'carts', to: 'carts#show'
  post '/add_item', to: 'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  post '/delete_item', to: 'carts#delete_item'
  resources :carts do
    collection do
      get :confirm
      get :complete
      get :save_user
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :carriage, optional: true
    belongs_to :user, optional: true
    has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :setup_order!

    def show
        @orders = current_cart.orders
    end

    def add_item
        if @order.blank?
            @order = current_cart.orders.build(item_id: params[:item_id])
        end

        @order.quantity = @order.quantity.to_i + params[:quantity].to_i
        @order.save

        redirect_to '/carts'
    end

    def update_item
        @order.update(quantity: params[:quantity].to_i)
        redirect_to '/carts'
    end

    def delete_item
        @order.destroy
        redirect_to '/carts'
    end

    def save_user
        if user_signed_in?
            @user_id = current_user.id
            @carriage_id = current_user.prefecture.id
            current_cart.update(user_id: @user_id, carriage_id: @carriage_id)
            @orders = current_cart.orders
            @orders.update(user_id: @user_id)
            redirect_to '/carts/confirm'
        else
            redirect_to '/users/sign_in'
        end
    end

    def confirm
        @user = current_user
        @orders = current_cart.orders

        @total_item_price = 0
        @total_quantity = 0
        @total_price = 0
        @orders.each do |order|
            # 商品名（さくらんぼ）
            @item_name = order.item.name
            # 商品名２（１Kgバラ）
            @item_second_name = order.item.second_name
            # １商品の金額
            @item_price = order.item.price
            # １商品の合計金額
            @item_total = (order.item.price * order.quantity)
            @total_item_price += @item_total
            # 全数量
            @total_quantity += order.quantity
            # 送料の合計金額
            @carriage_total = current_cart.carriage.price * @total_quantity 
            # 全商品と送料を足した最終合計金額
            @total_price = @total_item_price + @carriage_total
        end

        current_cart.update(total_price: @total_price)
    end

    def complete
        current_cart.update(date_time: Time.zone.now)
        OrderCompleteMailer.send_when_order_complete(current_user).deliver
        session[:cart_id] = nil
    end


    
    private

    def setup_order!
        @order = current_cart.orders.find_by(item_id: params[:item_id])
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/complete.html.erb
<%= render 'items/header' %>
<h2>注文を確定しました<br />
またのご利用お待ちしております</h2>

<p>ご登録頂いたアドレス宛にご注文完了のお知らせを送信いたしました。<br />
しばらく経ってもメールが届かない場合、お問い合わせページからご連絡をお願い致します。</p>

<%= link_to '商品一覧へ戻る', '/items' %>
<%= render 'items/footer' %>

app/views/carts/confirm.html.erb
<%= render 'items/header' %>
<h2>注文確認</h2>
<h3 class="confirm_user">お届け先/お客様登録情報</h3>
<div class="user_info">
    <p><span>お名前</span>：<%= @user.name %> 様</p>
    <p><span>電話番号</span>：<%= @user.phone %></p>
    <p><span>メールアドレス</span>：<%= @user.email %></p>
    <p><span>郵便番号</span>：<%= @user.postcode %></p>
    <p><span>住所</span>：<%= @user.prefecture.name %><%= @user.city %><%= @user.other_address %></p>
    <%= link_to '変更する', '/users/edit', class: "btn_edit_user" %>
</div>

<div class="total_price">
    <p>合計金額</p>
    <p>¥<%= @total_price.to_s(:delimited) %></p>
</div>

<% @orders.each do |order| %>
<div class="total_item">
    <p><%= @item_name %></p>
    <p><%= @item_second_name %></p>
    <p>¥<%= @item_price.to_s(:delimited) %></p>
    <p>×</p>
    <p><%= order.quantity %></p>
    <p>=</p>
    <p>¥<%= (order.item.price * order.quantity).to_s(:delimited) %></p>
</div>
<% end %>

<div class="total_postage">
    <p>送料</p>
    <p>¥<%= current_cart.carriage.price %></p>
    <p>×</p>
    <p><%= @total_quantity %></p>
    <p>=</p>
    <p>¥<%= @carriage_total.to_s(:delimited) %></p>
</div>

<%= button_to '注文確定', {controller: 'carts', action: 'complete'}, {method: :get, class: "btn_complete"} %>
<%= link_to 'カート画面に戻る', '/carts', class: "btn_return_cart"%>
<%= render 'items/footer' %>

app/views/carts/show.html.erb
<%= render 'items/header' %>
<div class="heading_cart">
</div>
<h2>カート</h2>
<div class="items">
    <% if @orders.blank? %>
        <h3 class="empty_cart"><%= "カートは空です" %></h3>
    <% end %>
    <% @orders.each do |order| %>
    <div class="item">
    <%= image_tag order.item.image_path %>
    <h3 class="item_name"><%= order.item.name %></h3>
    <h3 class="item_second_name"><%= order.item.second_name %></h3>
    <h3 class="item_price">¥<%= order.item.price %></h3>
    <h4 class="description"><%= order.item.description %></h4>
        <%= form_with url: update_item_path do |f| %>
            <div class="field">
                <%= f.label :quantity, "購入数", class:"order_quantity" %>
                <%= f.number_field :quantity, min:1,max:99, value: order.quantity, class:"number_field" %>
                <%= f.hidden_field :item_id, :value => order.item.id %>
            </div>
            <div class="action">
                <%= f.submit "変更する", class:"btn_change_quantity" %>
            </div>
        <% end %>
        <%= form_with url: delete_item_path do |f| %>
            <div class="field">
                <%= f.hidden_field :item_id, :value => order.item.id %>
            </div>
            <div class="action">
                <%= f.submit "削除", class:"btn_delete_item" %>
            </div>
        <% end%>
    </div>
    <% end %>
</div>
<% if @orders.blank? %>
    <%= button_to '商品一覧へ', {controller: 'items', action: 'index'}, {method: :get, class:"btn_item_index"} %>
<% else %>
    <div class="action">
        <%= button_to '商品一覧へ', {controller: 'items', action: 'index'}, {method: :get, class:"btn_item_index"} %>
    </div>
    <div class="action">
        <%= button_to 'レジへ進む', {controller: 'carts', action: 'save_user'}, {method: :get, class:"btn_go_confirm"} %>
    </div>
<% end %>
<%= render 'items/footer' %>