config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions"
  }
  get '/users', to: redirect("/users/sign_up")
  
  namespace :api, { format: 'json' } do
    # resources :favorites, only: [:index, :create, :destroy]
    post '/favorites', to: 'favorites#create'
    delete '/favorite/delete', to: 'favorites#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'displays#home'
  resources :displays do
    collection do
      get 'home'
      get 'company'
      get 'contact'
      get 'info'
    end
  end
  
  get 'company', to: 'displays#company'
  get 'contact', to: 'displays#contact'
  get 'info', to: 'displays#info'
  get 'items', to: 'items#index'
  get 'carts', to: 'carts#show'
  post '/add_item', to: 'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  post '/delete_item', to: 'carts#delete_item'
  resources :carts do
    collection do
      get :confirm
      get :complete
      get :save_user
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :order, optional: true
    has_many :favorites
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.all
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.erb
<div class="footer">
<ul class="footer_ul">
    <li><%= link_to image_tag('logo.png'), '/', class: "logo_footer" %></li>
    <li class="footer_li"><%= link_to "商品一覧", '/items' , class: "footer_menu_text"%></li>    
    <li class="footer_li"><%= link_to "お支払い・配送", '/info', class: "footer_menu_text" %></li> 
    <li class="footer_li"><%= link_to "果樹園紹介", '/company', class: "footer_menu_text" %></li> 
    <li class="footer_li"><%= link_to "お問い合わせ", '/contact', class: "footer_menu_text" %></li> 
</ul>
<p>Copyright © 2019 鈴木果樹園 All Rights Reserved.</p>
</div>

app/views/items/_header.html.erb
<ul class="menu">
    <li><%= link_to image_tag('logo.png'), '/' %></li>
    <li><%= link_to "商品一覧", '/items' , class: "menu_text"%></li>    
    <li><%= link_to "お支払い・配送", '/info', class: "menu_text" %></li> 
    <li><%= link_to "果樹園紹介", '/company', class: "menu_text" %></li> 
    <li><span><%= link_to "お問い合わせ", '/contact', class: "menu_text" %></span></li> 
  <% if user_signed_in? %>
    <li class="mypage_button"><%= link_to "マイページ", edit_user_registration_path, class: 'navbar-link' %></li>
    <li class="logout_button"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'navbar-link'  %></li>
  <% else %>
    <li class="login_button"><%= link_to "ログイン", new_user_session_path, class: 'login'  %></li>
  <% end %>
  <li class="check_cart"><%= link_to '/carts' do %><%= image_tag 'cart.png' %>カートを見る<% end %></li>
</ul>

app/views/items/index.html.erb
<%= render 'header' %>
<div class="heading", style="background-image:url(<%= asset_path "heading_items.png" %>)">
    <h2 class="heading_title">商品一覧</h2>
</div>
<div class="items">
    <div id="app">
        <% @items.each do |item| %>
            <div class="item">
                <%= image_tag item.image_path %>
                <h3 class="item_name"><%= item.name %></h3>
                <h3 class="item_second_name"><%= item.second_name %></h3>
                <h3 class="item_price">¥<%= item.price %></h3>
                <h4 class="description"><%= item.description %></h4>
                    <%= form_with url: add_item_path do |f| %>
                        <div class="field_quantity">
                            <%= f.label :quantity, "購入数", class:"order_quantity" %>
                            <%= f.number_field :quantity, min:1,max:99, class:"number_field"%>
                            <%= f.hidden_field :item_id, :value => item.id %>
                        </div>
                        <div class="action">
                            <%= f.submit "カートに入れる", class: "btn_add_cart" %>
                        </div>
                    <% end %>
                <% if user_signed_in? %> 
                    <like-component v-bind:user-id='<%= current_user.id %>' v-bind:item-id='<%= item.id %>' v-bind:favorite='<%= !current_user.hoge(item.id).nil? %>'></like-component>
                <% end %>
            </div>
        <% end %>
    </div>
</div>
<%= render 'footer' %>
<%= javascript_pack_tag 'hello_vue' %>